# Unbind the default prefix (Ctrl-b)
unbind C-b
#set-option -g prefix None
bind M-a send-prefix

# Pane navigation with Alt + n/e/u/i
bind -n M-n select-pane -L
bind -n M-e select-pane -D
bind -n M-u select-pane -U
bind -n M-i select-pane -R

# Split panes: Alt + v (vertical), Alt + s (horizontal)
bind -n M-h split-window -h
bind -n M-v split-window -v

# Resize panes with Alt + Shift + H/J/K/L
bind -n M-N resize-pane -L 5
bind -n M-E resize-pane -D 5
bind -n M-U resize-pane -U 5
bind -n M-I resize-pane -R 5

# Window controls
bind -n M-c new-window
bind -n M-x kill-window
bind -n M-w previous-window
bind -n M-f next-window

# Kill pane
bind -n M-q kill-pane

# Reload config
bind -n M-r source-file ~/.tmux.conf \; display-message "Config reloaded"

